Update qdl.md
The build also depends on libudev-dev without which the compiler would return following error.

qdl.c:43:10: fatal error: libudev.h: No such file or directory
 #include <libudev.h>